plugin:
    has_options: false
    icon: res_wiki.png

    resources:
        - name: icap_wiki
          class: Icap\WikiBundle\Entity\Wiki
          is_visible: true
          is_browsable: false
          icon: res_wiki.png